<!doctype html><html lang=en-us dir=ltr><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta name=description content="Today, while working on Friendly-traceback (
improved documentation
!) as I have been doing a lot recently, I came into an odd SyntaxError case:
The inconsistent behaviour is so tiny, that I doubt most people would notice - including myself before working on Friendly-traceback. This is SyntaxError that is not picked up by flake8; however, pylint does pick it up. By Python, I mean CPython.¬†After trying to figure out why this case was different, I downloaded Pypy and saw that Pypy did not show the odd behaviour."><title>A tiny Python exception oddity</title><link rel=canonical href=https://Nexus-Security.github.io/posts/2016-09-09-a-tiny-python-exception-oddity/><link rel=stylesheet href=/scss/style.min.450926226e724574a6b936335ea06111f8aeb253d932c86cb2cc807341cd2889.css><meta property="og:title" content="A tiny Python exception oddity"><meta property="og:description" content="Today, while working on Friendly-traceback (
improved documentation
!) as I have been doing a lot recently, I came into an odd SyntaxError case:
The inconsistent behaviour is so tiny, that I doubt most people would notice - including myself before working on Friendly-traceback. This is SyntaxError that is not picked up by flake8; however, pylint does pick it up. By Python, I mean CPython.¬†After trying to figure out why this case was different, I downloaded Pypy and saw that Pypy did not show the odd behaviour."><meta property="og:url" content="https://Nexus-Security.github.io/posts/2016-09-09-a-tiny-python-exception-oddity/"><meta property="og:site_name" content="ZYChimne"><meta property="og:type" content="article"><meta property="article:section" content="Posts"><meta property="article:published_time" content="2019-12-17T01:41:00+01:00"><meta property="article:modified_time" content="2019-12-17T01:41:00+01:00"><meta name=twitter:title content="A tiny Python exception oddity"><meta name=twitter:description content="Today, while working on Friendly-traceback (
improved documentation
!) as I have been doing a lot recently, I came into an odd SyntaxError case:
The inconsistent behaviour is so tiny, that I doubt most people would notice - including myself before working on Friendly-traceback. This is SyntaxError that is not picked up by flake8; however, pylint does pick it up. By Python, I mean CPython.¬†After trying to figure out why this case was different, I downloaded Pypy and saw that Pypy did not show the odd behaviour."></head><body class=article-page><script>(function(){const e="StackColorScheme";localStorage.getItem(e)||localStorage.setItem(e,"auto")})()</script><script>(function(){const t="StackColorScheme",e=localStorage.getItem(t),n=window.matchMedia("(prefers-color-scheme: dark)").matches===!0;e=="dark"||e==="auto"&&n?document.documentElement.dataset.scheme="dark":document.documentElement.dataset.scheme="light"})()</script><div class="container main-container flex on-phone--column extended"><aside class="sidebar left-sidebar sticky"><button class="hamburger hamburger--spin" type=button id=toggle-menu aria-label="Toggle Menu">
<span class=hamburger-box><span class=hamburger-inner></span></span></button><header><figure class=site-avatar><a href=/><img src=/img/avatar_hu8b78332b6420dc9affabe23720d11e63_1937019_300x0_resize_q75_box.jpg width=300 height=300 class=site-logo loading=lazy alt=Avatar></a>
<span class=emoji>üçá</span></figure><div class=site-meta><h1 class=site-name><a href=/>ZYChimne</a></h1><h2 class=site-description>Computer Science, Wuhan University</h2></div></header><ol class=social-menu><li><a href=https://github.com/ZYChimne target=_blank title=GitHub><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-github" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentcolor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M9 19c-4.3 1.4-4.3-2.5-6-3m12 5v-3.5c0-1 .1-1.4-.5-2 2.8-.3 5.5-1.4 5.5-6a4.6 4.6.0 00-1.3-3.2 4.2 4.2.0 00-.1-3.2s-1.1-.3-3.5 1.3a12.3 12.3.0 00-6.2.0C6.5 2.8 5.4 3.1 5.4 3.1a4.2 4.2.0 00-.1 3.2A4.6 4.6.0 004 9.5c0 4.6 2.7 5.7 5.5 6-.6.6-.6 1.2-.5 2V21"/></svg></a></li><li><a href=https://twitter.com/ZChimne target=_blank title=Twitter><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-twitter" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentcolor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M22 4.01c-1 .49-1.98.689-3 .99-1.121-1.265-2.783-1.335-4.38-.737S11.977 6.323 12 8v1c-3.245.083-6.135-1.395-8-4 0 0-4.182 7.433 4 11-1.872 1.247-3.739 2.088-6 2 3.308 1.803 6.913 2.423 10.034 1.517 3.58-1.04 6.522-3.723 7.651-7.742a13.84 13.84.0 00.497-3.753C20.18 7.773 21.692 5.25 22 4.009z"/></svg></a></li></ol><ol class=menu id=main-menu><li><a href=/><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-home" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentcolor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z"/><polyline points="5 12 3 12 12 3 21 12 19 12"/><path d="M5 12v7a2 2 0 002 2h10a2 2 0 002-2v-7"/><path d="M9 21v-6a2 2 0 012-2h2a2 2 0 012 2v6"/></svg><span>Home</span></a></li><li><a href=/about-me/><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentcolor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z"/><circle cx="12" cy="7" r="4"/><path d="M6 21v-2a4 4 0 014-4h4a4 4 0 014 4v2"/></svg><span>About Me</span></a></li><div class=menu-bottom-section><li id=dark-mode-toggle><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-toggle-left" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentcolor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z"/><circle cx="8" cy="12" r="2"/><rect x="2" y="6" width="20" height="12" rx="6"/></svg><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-toggle-right" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentcolor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z"/><circle cx="16" cy="12" r="2"/><rect x="2" y="6" width="20" height="12" rx="6"/></svg><span>Dark Mode</span></li></div></ol></aside><main class="main full-width"><article class=main-article><header class=article-header><div class=article-details><div class=article-title-wrapper><h2 class=article-title><a href=/posts/2016-09-09-a-tiny-python-exception-oddity/>A tiny Python exception oddity</a></h2></div><footer class=article-time><div><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar-time" width="56" height="56" viewBox="0 0 24 24" stroke-width="2" stroke="currentcolor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z"/><path d="M11.795 21H5a2 2 0 01-2-2V7a2 2 0 012-2h12a2 2 0 012 2v4"/><circle cx="18" cy="18" r="4"/><path d="M15 3v4"/><path d="M7 3v4"/><path d="M3 11h16"/><path d="M18 16.496V18l1 1"/></svg><time class=article-time--published>Dec 17, 2019</time></div><div><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-clock" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentcolor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z"/><circle cx="12" cy="12" r="9"/><polyline points="12 7 12 12 15 15"/></svg><time class=article-time--reading>5 minute read</time></div></footer></div></header><section class=article-content><p><img src=https://1.bp.blogspot.com/-qnDvCh03Vx8/XfWGx3OO-xI/AAAAAAAAFFQ/l5K_dR0hC9cRQycaYtYO8dmppmwH1jq2ACLcBGAsYHQ/w1200-h630-p-k-no-nu/cpython3.7.png loading=lazy></p><p>Today, while working on Friendly-traceback (</p><p><a class=link href=https://aroberge.github.io/friendly-traceback-docs/docs/html/ target=_blank rel=noopener>improved documentation</a></p><p>!) as I have been doing a lot recently, I came into an odd SyntaxError case:</p><ul><li>The inconsistent behaviour is so tiny, that I doubt most people would notice - including myself before working on Friendly-traceback.</li><li>This is SyntaxError that is <strong>not</strong> picked up by flake8; however, pylint does pick it up.</li><li>By Python, I mean CPython.¬† After trying to figure out why this case was different, I downloaded Pypy and saw that Pypy did not show the odd behaviour.</li><li>To understand the origin of this different behaviour, one needs to look at some obscure inner parts of the CPython interpreter.</li><li><strong>This would likely going to be found totally irrelevant by 99.999% of Python programmers.</strong> If you are not the type of person who is annoyed by tiny oddities, you probably do not want to read any further.</li></ul><p>You have been warned.</p><h2 id=normal-behaviour>Normal behaviour</h2><p>When Python finds a SyntaxError, it flags its location.¬† Let&rsquo;s have a look at a simple case, using CPython 3.7.</p><p>Notice how it indicates where it found the error, as shown by the red arrow: this happened when it reached a token that was inconsistent with the code entered so far. According to my experience until today, this seemed to be always the case.¬† Note that using CPython 3.6 yields exactly the same behaviour, and unhelpful error message.</p><p>Before discussing the case with a different behaviour, let&rsquo;s make a detour and look at Pypy&rsquo;s handling of the same case.</p><p>Same location indicated, but a much more helpful error message, even though this is version 3.6.¬† This improved error message was discussed in this</p><p><a class=link href=https://morepypy.blogspot.com/2018/04/improving-syntaxerror-in-pypy.html target=_blank rel=noopener>Pypy blog post</a></p><p>.¬† I strongly suspect that this is what lead to this improved error message in CPython 3.8.</p><p>Same error message as Pypy &mldr; but the exact location of the error, previously indicated by ^, no longer appears - which could be unfortunate when nested parenthesis (including square and curly brackets) are present.</p><p>What about Friendly-traceback you ask? I thought you never would! ;-)¬†¬†</p><p>Well, here&rsquo;s the information when using CPython 3.7.</p><p>The line about not having enough information from Python refers to the unhelpful message (&ldquo;invalid syntax&rdquo;). Hopefully you will agree that the information given by Friendly-traceback would be generally more useful, and especially more so for beginners.¬† ¬†</p><p>But enough about this case. It is time to look at the odd behaviour one.</p><h2 id=odd-case>Odd case</h2><p>Consider the following:</p><p>Having a variable declared both as a global and nonlocal variable is not allowed.¬† Let see what happens when this is executed by Pypy.</p><p>So, pypy processed the file passed the nonlocal statement and flagged the location where it encountered a statement which was inconsistent with everything that had been read so far: it thus flagged that as the location of the error.</p><p>Now, what happens with CPython:</p><p>The location flagged is one line earlier. The nonlocal statement is flagged as problematic but, reading the code up to that point, there is no indication that a global statement was encountered before.</p><p>Note that, changing the order of the two statements does not change the result: pypy shows the beginning of the second statement (line 6) as the problem, whereas CPython always shows the line before.</p><h2 id=why-does-it-matter-to-me>Why does it matter to me?</h2><p>If you go back to the first case I discussed, with the unmatched parenthesis, in Friendly-traceback, I rely on the location of the error shown by Python to indicate where the problem arose and, when appropriate, I look *back* to also show where the potential problem started.¬† Unfortunately, I cannot do that in this case with CPython.</p><h2 id=why-is-this-case-handled-differently-by-cpython>Why is this case handled differently by CPython?</h2><p>While I have some general idea of how the CPython interpreter works, I absolutely do not understand well enough to claim with absolute certainty how this situation arise.¬† Please, feel free to leave a comment to correct the description below if it is incorrect.</p><p>¬†My understanding is the following:</p><p>After breaking down a file into tokens, parsing it according to the rules of the Python grammar, an abstract syntax tree (AST) is constructed if no syntax error is found.¬† The nonlocal/global problem noted is not picked up by CPython up to that point - which also explains why flake8 would not find it as it relies on the AST, and does not actually executes the code.¬† (I&rsquo;m a bit curious as to how Pylint does &mldr; I&rsquo;ll probably have to look into it when I have more time).</p><p>Using the AST, a control flow graph is created and various &ldquo;frames&rdquo; are created with links (GOTOs, under a different name&mldr;) joining different parts.¬† It is at that point that relationships between variables in different frames is examined in details.¬† Pictorially, this can be represented as follows:</p><p>(This image was taken from</p><p><a class=link href=https://eli.thegreenplace.net/2010/09/20/python-internals-symbol-tables-part-2 target=_blank rel=noopener>this blog post by Eli Bendersky</a></p><p>)¬† In terms of the actual code, it is in the</p><p><a class=link href=https://github.com/python/cpython/blob/master/Python/symtable.c target=_blank rel=noopener>CPython symtable.c file</a></p><p>. At that point, errors are not found by scanning lines of code linearly, but rather by visiting nodes in the AST in some deterministic fashion &mldr; which leads to the oddity mentioned previously: CPython consistently shows the first of two statements as the source of the problem, whereas Pypy (which relies on some other method) shows the second, which is consistent with the way it shows the location of all SyntaxError messages.</p><h2 id=conclusion>Conclusion</h2><p>For Friendly-traceback, this likely means that for such cases, and unlike the mismatched parenthesis case, I will not attempt to figure out which two lines are problematic, and will simply expand slightly on the terse one liner given by Python (and in a way that can be translated into languages other than English).</p><p>from Hacker News <a class=link href=https://ift.tt/2RTiRiX target=_blank rel=noopener>https://ift.tt/2RTiRiX</a></p></section><footer class=article-footer><section class=article-copyright><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-copyright" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentcolor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z"/><circle cx="12" cy="12" r="9"/><path d="M14.5 9a3.5 4 0 100 6"/></svg><span>Licensed under CC BY-NC-SA 4.0</span></section></footer></article><footer class=site-footer><section class=copyright>&copy;
2020 -
2022 ZYChimne</section><section class=powerby>Built with <a href=https://gohugo.io/ target=_blank rel=noopener>Hugo</a><br>Theme <b><a href=https://github.com/CaiJimmy/hugo-theme-stack target=_blank rel=noopener data-version=3.11.0>Stack</a></b> designed by <a href=https://jimmycai.com target=_blank rel=noopener>Jimmy</a></section></footer><div class=pswp tabindex=-1 role=dialog aria-hidden=true><div class=pswp__bg></div><div class=pswp__scroll-wrap><div class=pswp__container><div class=pswp__item></div><div class=pswp__item></div><div class=pswp__item></div></div><div class="pswp__ui pswp__ui--hidden"><div class=pswp__top-bar><div class=pswp__counter></div><button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
<button class="pswp__button pswp__button--share" title=Share></button>
<button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
<button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button><div class=pswp__preloader><div class=pswp__preloader__icn><div class=pswp__preloader__cut><div class=pswp__preloader__donut></div></div></div></div></div><div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap"><div class=pswp__share-tooltip></div></div><button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
<button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button><div class=pswp__caption><div class=pswp__caption__center></div></div></div></div></div><script src=https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.min.js integrity="sha256-ePwmChbbvXbsO02lbM3HoHbSHTHFAeChekF1xKJdleo=" crossorigin=anonymous defer></script><script src=https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe-ui-default.min.js integrity="sha256-UKkzOn/w1mBxRmLLGrSeyB4e1xbrp4xylgAWb3M42pU=" crossorigin=anonymous defer></script><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/default-skin/default-skin.css integrity="sha256-c0uckgykQ9v5k+IqViZOZKc47Jn7KQil4/MP3ySA3F8=" crossorigin=anonymous><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.css integrity="sha256-SBLU4vv6CA6lHsZ1XyTdhyjJxCjPif/TRkjnsyGAGnE=" crossorigin=anonymous></main><aside class="sidebar right-sidebar sticky"><section class="widget archives"><div class=widget-icon><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-hash" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentcolor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z"/><line x1="5" y1="9" x2="19" y2="9"/><line x1="5" y1="15" x2="19" y2="15"/><line x1="11" y1="4" x2="7" y2="20"/><line x1="17" y1="4" x2="13" y2="20"/></svg></div><h2 class="widget-title section-title">Table of contents</h2><div class=widget--toc><nav id=TableOfContents><ol><li><a href=#normal-behaviour>Normal behaviour</a></li><li><a href=#odd-case>Odd case</a></li><li><a href=#why-does-it-matter-to-me>Why does it matter to me?</a></li><li><a href=#why-is-this-case-handled-differently-by-cpython>Why is this case handled differently by CPython?</a></li><li><a href=#conclusion>Conclusion</a></li></ol></nav></div></section></aside></div><script src=https://cdn.jsdelivr.net/npm/node-vibrant@3.1.5/dist/vibrant.min.js integrity="sha256-5NovOZc4iwiAWTYIFiIM7DxKUXKWvpVEuMEPLzcm5/g=" crossorigin=anonymous></script><script type=text/javascript src=/ts/main.js defer></script>
<script>(function(){const e=document.createElement("link");e.href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap",e.type="text/css",e.rel="stylesheet",document.head.appendChild(e)})()</script></body></html>